import type { Metadata } from "next";
// import { Geist, Geist_Mono, Caveat } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

// const caveat = Caveat({
//   variable: "--font-caveat",
//   subsets: ["latin"],
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

import { caveatRegular, caveatMedium, caveatSemiBold, caveatBold } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "CarOn.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${caveatRegular.variable} ${caveatMedium.variable} ${caveatSemiBold.variable} ${caveatBold.variable}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
